[package]
name = "zeroize_alloc"
version = "0.1.0"
authors = ["Aiden McClelland <aiden.mcclelland@saltlending.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]